### PR TITLE
🔓 Remove "access restricted"

### PR DESCRIPTION
**Pull request by Burtchen**
### Summary of the issue
Making the package public so our CI/CD and local installations have an easier time.

### CODE REVIEW

**Comment by jonathan-reisdorf** [comment]
If you also bump the package version, we can immediately re-deploy a public package :)

**Comment by varghesethomase** [comment]
@Burtchen can a publish be made without package update?

**Comment by jonathan-reisdorf** [comment]
@varghesethomase nope, npm requires a version bump, else publishing will fail bc the version already exists on npm

**Comment by varghesethomase** [comment]
Thank you @jonathan-reisdorf

**Pull request merged**
